[package]
name = "parity-codec"
description = "Lightweight, efficient, binary serialization and deserialization codec"
version = "2.1.5"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"

[dependencies]
arrayvec = { version = "0.4", default-features = false }
serde = { version = "1.0", optional = true }
parity-codec-derive = { version = "2.0", default-features = false, optional = true }

[features]
default = ["std"]
std = ["serde"]
derive = ["parity-codec-derive"]

[workspace]
members = [
	"derive",
]
